[package]
name = "lambda"
version = "0.0.1"
authors = ["Klas Segeljakt <klasseg@kth.se>"]
edition = "2018"
license = "MIT OR Apache-2.0"
build = "build.rs"

[lib]
proc-macro = true

[build-dependencies]
lalrpop = "0.17.1"

[dependencies]
lalrpop-util = "0.17.1"
regex = "1.2.1"
